import React from 'react';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer, Tooltip } from 'recharts';
import careerData from '../../data/careerData.json';
import jsPDF from 'jspdf'; // <--- IMPORT THIS

export default function CareerResult({ score, sectionScores, recommendation, info, onReset }) {
  
  // 1. CHART DATA
  const targetRole = info.targetRole || "Software Engineer";
  const benchmark = careerData.benchmarks[targetRole] || {};

  const data = [
    { subject: 'Soft Skills', A: sectionScores.softSkills, B: benchmark.softSkills, fullMark: 20 },
    { subject: 'Technical', A: sectionScores.technicalSkills, B: benchmark.technicalSkills, fullMark: 25 },
    { subject: 'Interest', A: sectionScores.interest, B: benchmark.interest, fullMark: 20 },
    { subject: 'Extracurricular Activities', A: sectionScores.extracurricular, B: benchmark.extracurricular, fullMark: 15 },
    { subject: 'Behavior', A: sectionScores.behavior, B: benchmark.behavior, fullMark: 20 },
  ];

 // --- NEW PDF FORMAT LOGIC ---
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // 1. Header
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185); // Blue
    doc.text("AlokPath AI - Career Report", margin, y);
    y += 10;

    // 2. Generated Info
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated for: ${info.name} (${info.id})`, margin, y);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, y);
    y += 15;

    // Divider
    doc.setLineWidth(0.5);
    doc.setDrawColor(200);
    doc.line(margin, y - 5, 190, y - 5);

    // 3. Student Details (List Format)
    doc.setFontSize(12);
    doc.setTextColor(0);
    
    doc.text(`Student Name:  ${info.name}`, margin, y); y += 8;
    doc.text(`Student ID:       ${info.id}`, margin, y); y += 8;
    doc.text(`Department:     ${info.dept}`, margin, y); y += 8;
    doc.text(`CGPA:             ${info.cgpa}`, margin, y); y += 12;

    // 4. Scores & Roles
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text(`Total Score: ${score}/100`, margin, y); y += 10;

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Target Role: ${targetRole}`, margin, y); y += 8;
    doc.text(`Recommended Domain: ${recommendation.domain}`, margin, y); y += 8;
    
    
    // 5. Skill Breakdown
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Skill Breakdown", margin, y); y += 10;

    doc.setFontSize(12);
    doc.setTextColor(0);
    data.forEach(item => {
        doc.text(`• ${item.subject}: ${item.A}/${item.fullMark}`, margin + 5, y);
        y += 7;
    });
    y += 5;

    // 6. Strategic Advice
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("AI Strategic Advice", margin, y); y += 8;

    doc.setFontSize(11);
    doc.setTextColor(50);
    const splitAdvice = doc.splitTextToSize(recommendation.advice, 170);
    doc.text(splitAdvice, margin, y);

    // 7. Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by AlokPath AI System", margin, 280);

    doc.save(`${info.name}_Career_Report.pdf`);
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <div className="bg-gray-800/90 backdrop-blur-xl p-8 rounded-3xl border border-gray-700 shadow-2xl max-w-6xl w-full animate-zoom-in">
        
        <h2 className="text-3xl font-bold text-white mb-2 text-center">Career Fit Analyzer</h2>
        <p className="text-gray-400 mb-8 text-center">
          Comparing you against an ideal <span className="text-blue-400 font-bold">{targetRole}</span>
        </p>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
          
          {/* Chart Section */}
          <div className="h-96 w-full relative bg-gray-900/50 rounded-3xl border border-gray-600 p-4">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="70%" data={data}>
                <PolarGrid stroke="#4B5563" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: '#9CA3AF', fontSize: 12, fontWeight: 'bold' }} />
                <PolarRadiusAxis angle={30} domain={[0, 25]} tick={false} axisLine={false} />
                <Radar name={`Ideal ${targetRole}`} dataKey="B" stroke="#3B82F6" strokeWidth={2} fill="#3B82F6" fillOpacity={0.3} />
                <Radar name="You" dataKey="A" stroke="#10B981" strokeWidth={3} fill="#10B981" fillOpacity={0.6} />
                <Tooltip contentStyle={{ backgroundColor: '#1F2937', borderColor: '#374151', color: '#fff' }} />
              </RadarChart>
            </ResponsiveContainer>
            <div className="absolute bottom-4 w-full flex justify-center gap-6 text-xs font-bold">
                <div className="flex items-center gap-2 text-green-400"><div className="w-3 h-3 bg-green-500 rounded-full"></div> You</div>
                <div className="flex items-center gap-2 text-blue-400"><div className="w-3 h-3 bg-blue-500 rounded-full opacity-50"></div> Ideal {targetRole}</div>
            </div>
          </div>

          {/* Text Analysis */}
          <div className="text-left space-y-6">
             <div className="bg-gray-900/50 p-6 rounded-2xl border border-gray-600">
                <h4 className="text-xs font-bold text-blue-400 uppercase tracking-wider mb-4">Gap Analysis</h4>
                <ul className="space-y-3">
                  {data.map((item, i) => {
                    const gap = item.A - item.B;
                    let message = gap >= 0 ? "✅ Excellent" : (gap > -5 ? "⚠️ Needs work" : "❌ Critical Gap");
                    let color = gap >= 0 ? "text-green-400" : (gap > -5 ? "text-yellow-400" : "text-red-400");
                    return (
                      <li key={i} className="text-sm border-b border-gray-700 pb-2 last:border-0 flex justify-between">
                        <span className="text-white font-bold">{item.subject}</span>
                        <span className={color}>{message} </span>
                      </li>
                    )
                  })}
                </ul>
             </div>
          </div>
        </div>

        {/* --- BUTTONS --- */}
        <div className="mt-10 flex flex-col md:flex-row justify-center gap-4 border-t border-gray-700 pt-8">
            <button 
                onClick={handleDownloadPDF} // <--- CONNECTED HERE
                className="flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-500 text-white font-bold py-3 px-8 rounded-full shadow-lg transition transform hover:scale-105"
            >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                Download AI Report (PDF)
            </button>

            <button onClick={onReset} className="text-gray-400 hover:text-white px-6 py-3 rounded-full border border-gray-600 hover:border-gray-400 transition">
                Check Another Role
            </button>
        </div>

      </div>
    </div>
  );
}